In [4]:
import numpy as np

In [2]:
np.__version__

NameError: name 'np' is not defined

 ## Create and Read

#### 1D Array

In [ ]:
arr1 = np.array([1,2,3,4,5])
arr1

In [ ]:
type(arr1)

In [ ]:
 arr1.shape

In [ ]:
arr1.dtype

In [ ]:
arr1.ndim

In [ ]:
arr1.size

 ##### 2D Array

In [ ]:
arr2 = np.array([[1, 4, 5], [6, 7, 8]])
arr2

In [ ]:
arr2.ndim

In [ ]:
arr2.shape # ( row, column )

In [ ]:
arr2.dtype

In [ ]:
arr2.size

#### 3D Array

In [18]:
arr3 = np.array([[[1,4,5], [6,7,4]], [[3,4,5], [1, 2,4]]])
arr3

array([[[1, 4, 5],
        [6, 7, 4]],

       [[3, 4, 5],
        [1, 2, 4]]])

In [10]:
arr3.ndim

3

In [11]:
arr3.shape

(1, 4, 3)

In [12]:
arr3.size

12

In [5]:
full = np.full((3,2,3),9)
full

array([[[9, 9, 9],
        [9, 9, 9]],

       [[9, 9, 9],
        [9, 9, 9]],

       [[9, 9, 9],
        [9, 9, 9]]])

In [7]:
ones = np.ones((3, 2, 3))
ones

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

In [22]:
arr3

array([[[1, 4, 5],
        [6, 7, 4]],

       [[3, 4, 5],
        [1, 2, 4]]])

In [27]:
arr3[0][1][2]

np.int64(4)

In [30]:
arr3[0:1]

array([[[1, 4, 5],
        [6, 7, 4]]])

In [31]:
arr3[-1]

array([[3, 4, 5],
       [1, 2, 4]])

In [32]:
arr3[0,1,1]

np.int64(7)

## Update & Delete

In [33]:
a1 = np.random.rand(2, 3, 2)
a2 = np.random.rand(2, 3, 2)

In [34]:
a1

array([[[0.53907469, 0.39324321],
        [0.21293111, 0.61912543],
        [0.32881186, 0.7745081 ]],

       [[0.77067043, 0.41930941],
        [0.62908665, 0.28393289],
        [0.15556107, 0.50153978]]])

In [35]:
a2

array([[[0.14748625, 0.66038593],
        [0.80628834, 0.41985528],
        [0.53866047, 0.00497209]],

       [[0.99060018, 0.78977243],
        [0.26555819, 0.38000513],
        [0.74940392, 0.9856586 ]]])

#### Basic Math Operations

In [36]:
np.add(a1, a2)

array([[[0.68656094, 1.05362914],
        [1.01921945, 1.03898072],
        [0.86747233, 0.7794802 ]],

       [[1.76127061, 1.20908184],
        [0.89464484, 0.66393802],
        [0.90496499, 1.48719838]]])

In [37]:
np.subtract(a1, a2)

array([[[ 0.39158844, -0.26714272],
        [-0.59335723,  0.19927015],
        [-0.20984861,  0.76953601]],

       [[-0.21992974, -0.37046303],
        [ 0.36352846, -0.09607224],
        [-0.59384286, -0.48411882]]])

In [38]:
np.multiply(a1, a2)

array([[[0.0795061 , 0.25969228],
        [0.17168387, 0.25994309],
        [0.17711795, 0.00385093]],

       [[0.76342627, 0.33115901],
        [0.16705911, 0.10789595],
        [0.11657807, 0.49434699]]])

In [39]:
np.divide(a1, a2)

array([[[  3.65508441,   0.59547485],
        [  0.26408804,   1.47461627],
        [  0.61042507, 155.77106634]],

       [[  0.77798334,   0.53092434],
        [  2.36892205,   0.74718172],
        [  0.20757973,   0.50883722]]])

#### Statistical Operations

In [50]:
sqrt = np.sqrt(64)
abs = np.abs(-2)
log = np.log(25)
power = np.power(2, 10)
mins = np.min(a1)
maxs = np.max(a2)

In [51]:
sqrt, abs, log, power, mins, maxs

(np.float64(8.0),
 np.int64(2),
 np.float64(3.2188758248682006),
 np.int64(1024),
 np.float64(0.1555610665317665),
 np.float64(0.9906001757245988))

In [52]:
arr3

array([[[1, 4, 5],
        [6, 7, 4]],

       [[3, 4, 5],
        [1, 2, 4]]])

In [53]:
arr3[0][1][2] = 21
arr3

array([[[ 1,  4,  5],
        [ 6,  7, 21]],

       [[ 3,  4,  5],
        [ 1,  2,  4]]])

In [57]:
arr3.sort()
arr3

array([[[ 1,  4,  5],
        [ 6,  7, 21]],

       [[ 3,  4,  5],
        [ 1,  2,  4]]])

In [67]:
arr3.shape

(2, 2, 3)

In [73]:
arr3_reshape = arr3.reshape((2, 1, -1))
arr3_reshape

array([[[ 1,  4,  5,  6,  7, 21]],

       [[ 3,  4,  5,  1,  2,  4]]])

In [75]:
arr3_reshape.shape

(2, 1, 6)

#### Appending and Inserting

In [82]:
zeroes = np.zeros((3, 2, 3))
zeroes

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [83]:
ones

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

In [89]:
apnd = np.append(zeroes, ones, axis= 0)
apnd

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

Insert

In [92]:
inserted_array = np.insert(zeroes, 1, ones, axis=0)
inserted_array

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [94]:
arr4 = np.random.rand(3, 2, 3)
arr4

array([[[0.62643882, 0.79891531, 0.33610391],
        [0.03246202, 0.04558862, 0.78872485]],

       [[0.05852974, 0.84884354, 0.75767344],
        [0.67645444, 0.88235798, 0.25210791]],

       [[0.87154162, 0.44809319, 0.57325484],
        [0.18841991, 0.86653117, 0.45101733]]])

In [96]:
#delete the array
arr5 = np.delete(arr4, 0, axis=1)
arr5

array([[[0.03246202, 0.04558862, 0.78872485]],

       [[0.67645444, 0.88235798, 0.25210791]],

       [[0.18841991, 0.86653117, 0.45101733]]])

In [97]:
np.save("New array", arr5)

In [98]:
np.load("New Array.npy")

array([[[0.03246202, 0.04558862, 0.78872485]],

       [[0.67645444, 0.88235798, 0.25210791]],

       [[0.18841991, 0.86653117, 0.45101733]]])